<?php
/**
 * SEAnamoly DummyData Partial Seeder
 *
 * @category   SEAnamoly DummyData Partial
 * @package    Seeder
 * @author     Sachin Pawaskar<spawaskar@unomaha.edu>
 * @copyright  2016-2018
 * @license    The MIT License (MIT)
 * @version    GIT: $Id$
 * @since      File available since Release 1.0.0
 */

use Illuminate\Database\Seeder;
use App\SkeletalBone;
use App\SkeletalElement;
use App\Anomaly;
use App\Org;
use App\Project;

class SEAnamolyPartialTableSeeder extends Seeder {
    
    public function run()
    {
        $dt = date_create();
        $sys = 'System';
        $org = Org::where('acronym', '=', 'UNO')->first()->id;
        $project = Project::where('name', '=', 'CoRA Demo')->first()->id;

        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '601']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '602']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '601']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '601']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '602']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '601']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Clavicle')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Rhomboid fossa'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '603']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Scapula')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Scapular foramen'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '201']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Humerus')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Septal aperture'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '202']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Humerus')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Septal aperture'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '201']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Humerus')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Septal aperture'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '202']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Humerus')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Septal aperture'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '201']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Humerus')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Septal aperture'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '809']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Thoracic vertebra 12')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Vertebral shift'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '819']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Thoracic vertebra 12')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Vertebral shift'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '812']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Thoracic vertebra 11')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Vertebral shift'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '813']])->first()->id;$sb_id = SkeletalBone::where('name', '=', 'Thoracic vertebra 12')->first()->id;$anomaly_id = Anomaly::where([['individuating_trait', '=', 'Vertebral shift'],['sb_id', '=' ,$sb_id]])->first()->id;DB::table('se_anomaly')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'anomaly_id'=> $anomaly_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
    }
}