<?php
/**
 * SEPathology DummyData Partial Seeder
 *
 * @category   SEPathology DummyData Partial
 * @package    Seeder
 * @author     Sachin Pawaskar<spawaskar@unomaha.edu>
 * @copyright  2016-2018
 * @license    The MIT License (MIT)
 * @version    GIT: $Id$
 * @since      File available since Release 1.0.0
 */

use Illuminate\Database\Seeder;
use App\SkeletalElement;
use App\Pathology;
use App\Org;
use App\Project;

class SEPathologyPartialTableSeeder extends Seeder {

    public function run()
    {
        $dt = date_create();
        $sys = 'System';
        $org = Org::where('acronym', '=', 'UNO')->first()->id;
        $project = Project::where('name', '=', 'CoRA Demo')->first()->id;

        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '802']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Morphology'],[ 'characteristics', '=', 'Spondylolysis']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Morphology','characteristics'=>'Spondylolysis','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '903']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Morphology'],[ 'characteristics', '=', 'Spina bifida']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Morphology','characteristics'=>'Spina bifida','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '509']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '805']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '806']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '807']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '808']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '809']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '810']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '818']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Morphology'],[ 'characteristics', '=', 'Spina bifida']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Morphology','characteristics'=>'Spina bifida','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219D'], ['designator', '=', '810']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219D'], ['designator', '=', '811']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219D'], ['designator', '=', '812']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '807']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '808']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '809']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '810']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '811']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '812']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '813']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '814']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '815']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Proliferative'],[ 'characteristics', '=', 'Lipping']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Proliferative','characteristics'=>'Lipping','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219F'], ['designator', '=', '810']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Lytic'],[ 'characteristics', '=', 'Schmorls node']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Lytic','characteristics'=>'Schmorls node','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219F'], ['designator', '=', '811']])->first()->id;$pathology_id = Pathology::where([['abnormality_category', '=', 'Lytic'],[ 'characteristics', '=', 'Schmorls node']])->first()->id;DB::table('se_pathology')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pathology_id'=> $pathology_id,'zone_id'=>null,'abnormality_category'=>'Lytic','characteristics'=>'Schmorls node','additional_information'=>'','created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
	}
}