<?php
/**
 * SEPair DummyData Partial Seeder
 *
 * @category   SEPair DummyData Partial
 * @package    Seeder
 * @author     Sachin Pawaskar<spawaskar@unomaha.edu>
 * @copyright  2016-2018
 * @license    The MIT License (MIT)
 * @version    GIT: $Id$
 * @since      File available since Release 1.0.0
 */

use Illuminate\Database\Seeder;
use App\SkeletalElement;
use App\Org;
use App\Project;

class SEPairPartialTableSeeder extends Seeder
{
    public function run()
    {
        $dt = date_create();
        $sys = 'System';
        $org = Org::where('acronym', '=', 'UNO')->first()->id;
        $project = Project::where('name', '=', 'CoRA Demo')->first()->id;

        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '402']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '401']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '603']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '604']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '203']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '204']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '205']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '206']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '403']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '404']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '403']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '404']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-235A'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-236C'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '403']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '404']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56B'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '403']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '404']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '405']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56C'], ['designator', '=', '406']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '203']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '204']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56D'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56E'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56F'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56F'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56F'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56F'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '201']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '202']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '203']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '204']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '401']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '402']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '901']])->first()->id;$pair_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56G'], ['designator', '=', '902']])->first()->id;DB::table('se_pair')->insert(array(array('org_id'=>$org,'project_id'=>$project,'se_id'=> $se_id,'pair_id'=> $pair_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
	}
}
