<?php
/**
 * SETaphonomy DummyData Partial Seeder
 *
 * @category   SETaphonomy DummyData Partial
 * @package    Seeder
 * @author     Sachin Pawaskar<spawaskar@unomaha.edu>
 * @copyright  2016-2018
 * @license    The MIT License (MIT)
 * @version    GIT: $Id$
 * @since      File available since Release 1.0.0
 */

use Illuminate\Database\Seeder;
use App\SkeletalElement;
use App\Taphonomy;
use App\Org;
use App\Project;

class SETaphonomyPartialTableSeeder extends Seeder
{
    public function run()
    {
        $dt = date_create();
        $sys = 'System';
        $org = Org::where('acronym', '=', 'UNO')->first()->id;
        $project = Project::where('name', '=', 'CoRA Demo')->first()->id;

        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '403']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-232C'], ['designator', '=', '404']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-01'], ['provenance2','=', 'X-234A'], ['designator', '=', '404']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '205']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '403']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '901']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-04'], ['provenance2','=', 'X-56A'], ['designator', '=', '902']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '201']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '401']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '402']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '403']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '405']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '601']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '603']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '604']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '701']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '702']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '703']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '704']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '705']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '706']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '707']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '708']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '709']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '710']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '711']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '712']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '713']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '714']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '715']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '716']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '717']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '718']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '719']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '720']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '721']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '722']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '723']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '724']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '725']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '726']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '801']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '802']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '803']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '804']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '805']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '806']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '807']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '808']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '809']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '810']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '811']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '812']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '813']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '814']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '815']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '816']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '817']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '818']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '819']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '820']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '821']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '822']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '823']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '824']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '901']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '902']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219A'], ['designator', '=', '903']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '402']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '707']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '708']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '713']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '714']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '716']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '717']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '801']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '802']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '803']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '804']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '805']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '806']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '807']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '808']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219B'], ['designator', '=', '810']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '504']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '505']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '506']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '507']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '508']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '509']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '704']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '705']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '706']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '708']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219C'], ['designator', '=', '710']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '804']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '805']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '806']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '807']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '808']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '809']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '810']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '811']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '812']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '813']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '814']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '815']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-05'], ['provenance2','=', 'X-219E'], ['designator', '=', '819']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-25'], ['provenance2','=', 'X-247C'], ['designator', '=', '902']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-27'], ['provenance2','=', 'X-184B'], ['designator', '=', '402']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-28'], ['provenance2','=', 'X-13B'], ['designator', '=', '510']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Staining'], ['type', '=', 'Rust'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-29'], ['provenance2','=', 'X-254B'], ['designator', '=', '602']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-29'], ['provenance2','=', 'X-254D'], ['designator', '=', '603']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-31'], ['provenance2','=', 'X-238 Femora'], ['designator', '=', '411']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-33'], ['provenance2','=', 'X-240A'], ['designator', '=', '602']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Staining'], ['type', '=', 'Rust'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-33'], ['provenance2','=', 'X-240F'], ['designator', '=', '403']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-37'], ['provenance2','=', 'X-237ABDEFG'], ['designator', '=', '220']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Physical'], ['type', '=', 'Cortical Exfoliation/Flaking'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-44'], ['provenance2','=', 'X-234E'], ['designator', '=', '202']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Oil Residue'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-44'], ['provenance2','=', 'X-234E'], ['designator', '=', '202']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
        $se_id = SkeletalElement::where([['accession_number', '=', 'UNO 2016-212'],[ 'provenance1', '=', 'G-46'], ['provenance2','=', 'X-222A'], ['designator', '=', '407']])->first()->id;$taphonomy_id = Taphonomy::where([[ 'branch', '=', 'Bio'],[ 'category', '=', 'Adherent Materials'], ['type', '=', 'Adipocere'],  ['subtype', '=', '']])->first()->id;DB::table('se_taphonomy')->insert(array(array('org_id'=>$org, 'project_id'=>$project,'se_id'=> $se_id,'taphonomy_id'=> $taphonomy_id,'created_by' => $sys, 'updated_by' => $sys, 'created_at' => $dt, 'updated_at' => $dt)));
	}
}
