@extends('layouts.app')

@section('title', config('app.name', 'CoRA')." ".$heading)

@section('content')
    @php
        $defaultProject = $theUser->getCurrentProject();
        $currentProject = $defaultProject;
        $SEactivity = $currentProject->se_activities_by_user($theUser, 10);
        $DNAactivity = $currentProject->dna_activities_by_user($theUser, 10);
    @endphp
    <v-row align="center" justify="center">
        <v-col cols="12" class="m-0 p-0">
            <user-profile-main
                    :flex_cols_md="2"
                    :flex_cols_sm="12"
                    :disabled="false"
                    :displaynamelabel= "'Name'"
                    :emaillabel= "'Email'"
                    :userrolelabel= "'Role'"
                    :cellphoneplaceholder= "555-555-5555"
                    :cellphonelabel= "'Cell Phone'"
                    :altphoneplaceholder=  "777-777-7777"
                    :altphonelabel= "'Alt Phone'"
                    :slackchannelplaceholder= "'https://slack.com/myChannel'"
                    :slackchannellabel= "'Slack Channel'"
                    :displaynamevmodel="{{json_encode($theUser->display_name, true)}}"
                    :emailvmodel="{{ json_encode($theUser->email, true) }}"
                    :userrolevmodel="{{ json_encode($theUser->role->name, true) }}"
                    :cellphonevmodel="{{ json_encode($theUser->cell_phone, true) }}"
                    :altphonevmodel="{{ json_encode($theUser->phone, true) }}"
                    :slackchannelvmodel="{{ json_encode($theUser->slack_channel, true) }}"
                    :profilephotovmodel="{{ json_encode($theUser->avatar, true) }}"

                    :linesperpagelabel="'Lines per page'"
                    :linesperpageoptions="{{$theUser->getProfileDisplayValues('lines_per_page')}}"
                    :linesperpagevmodel="{{$theUser->getProfileValue("lines_per_page")}}"
                    :linesperpagelabelhelp="'{{$theUser->getProfileHelp('lines_per_page')}}'"
                    :welcomescreenoptions="{{json_encode($theUser->getProfileValue("welcome_screen_on_startup"), true)}}"
                    :welcomescreenlabel="'Welcome Screen'"
                    :welcomescreenlabelhelp="'{{ $theUser->getProfileHelp('welcome_screen_on_startup') }}'"
                    :helpslideoutoptions="{{json_encode($theUser->getProfileValue('ui_right_sidebar_slideout_help'), true)}}"
                    :helpslideoutlabel="'Help Slideout'"
                    :helpslideoutlabelhelp="'{{ $theUser->getProfileHelp('ui_right_sidebar_slideout_help')}}'"

                    :notifyexportoptions="{{json_encode($theUser->getProfileValue("notify_export_import_completion"), true)}}"
                    :notifyexportlabel="'Data Transfer Job Completes'"
                    :notifyexportlabelhelp="'{{ $theUser->getProfileHelp('notify_export_import_completion') }}'"
                    :notifyreviewoptions="{{json_encode($theUser->getProfileValue('notify_se_review_completion')), true}}"
                    :notifyreviewlabel="'Remains Review Completes'"
                    :notifyreviewlabelhelp="'{{ $theUser->getProfileHelp('notify_se_review_completion')}}'"
                    :notifyviaemailoptions="{{json_encode($theUser->getProfileValue("notify_via_email"), true)}}"
                    :notifyviaemaillabel="'Email'"
                    :notifyviaemaillabelhelp="'{{ $theUser->getProfileHelp('notify_via_email') }}'"
                    :notifyviasmsoptions="{{json_encode($theUser->getProfileValue('notify_via_sms'), true)}}"
                    :notifyviasmslabel="'SMS to Mobile'"
                    :notifyviasmslabelhelp="'{{ $theUser->getProfileHelp('notify_via_sms')}}'"
                    :notifyviaslackoptions="{{json_encode($theUser->getProfileValue('notify_via_slack'), true)}}"
                    :notifyviaslacklabel="'Slack Notification'"
                    :notifyviaslacklabelhelp="'{{ $theUser->getProfileHelp('notify_via_slack')}}'"

                    :countries_options="{{json_encode($country_array, true)}}"
                    :languages_options="{{json_encode($language_codes, true)}}"
                    :timezones_options="{{json_encode($timezone_array, true)}}"
                    :default_country="{{json_encode($theUser->default_country, true)}}"
                    :default_language="{{json_encode($theUser->default_language, true)}}"
                    :default_time_zone="{{json_encode($theUser->default_timezone, true)}}"

                    :defaultprojectoptions="{{json_encode($list_projects, true)}}"
                    :defaultprojectlabel="'Default Project'"
                    :defaultprojectlabelhelp="'{{$theUser->getProfileHelp('default_project')}}'"
                    :defaultprojectvmodel="'{{$theUser->getProfileValue('default_project')}}'"
                    :useraccessionnumberlabel="'Accession Number'"
                    :useraccessionnumber="'{{$theUser->getProfileValue('accession')}}'"
                    :userprovenance1="'{{$theUser->getProfileValue('provenance1')}}'"
                    :userprovenance2="'{{$theUser->getProfileValue('provenance2')}}'"
                    :usermrulistspecimens="'{{$theUser->getProfileValue('mru_list_skeletalelements')}}'"
                    :userprovenance1label="'Provenance 1'"
                    :userprovenance2label="'Provenance 2'"
                    :usermrulistspecimenslabel="'MRU List Specimens'"
                    :defaultsearchoptions="{{$theUser->getProfileDisplayValues('default_search_option')}}"
                    :defaultsearchlabel="'Default Search Option'"
                    :defaultsearchlabelhelp="'{{$theUser->getProfileHelp('default_search_option')}}'"
                    :defaultsearchvmodel="'{{$theUser->getProfileValue('default_search_option')}}'"
                    :savelastsearchbyoptions="{{json_encode($theUser->getProfileValue("user_save_last_search_by"), true)}}"
                    :savelastsearchbylabel="'Save Last Search By'"
                    :savelastsearchbylabelhelp="'{{ $theUser->getProfileHelp('user_save_last_search_by') }}'"
                    :searchopeninnewbrowseroptions="{{json_encode($theUser->getProfileValue('se_search_open_in_new_browser_tab'), true)}}"
                    :searchopeninnewbrowserlabel="'Open Search in New Tab'"
                    :searchopeninnewbrowserlabelhelp="'{{ $theUser->getProfileHelp('se_search_open_in_new_browser_tab')}}'"
                    :useraccessionnumberlabelhelp="'{{ $theUser->getProfileHelp('accession') }}'"
                    :userprovenance1labelhelp="'{{ $theUser->getProfileHelp('provenance1') }}'"
                    :userprovenance2labelhelp="'{{ $theUser->getProfileHelp('provenance2') }}'"
                    :usermrulistspecimenslabelhelp="'{{ $theUser->getProfileHelp('mru_list_skeletalelements') }}'"
                    :senewredirecturllabel="'After creation of SE, redirect to Page'"
                    :senewredirecturloptions="{{$theUser->getProfileDisplayValues('se_new_redirect_url')}}"
                    :senewredirecturlvmodel="'{{$theUser->getProfileValue("se_new_redirect_url")}}'"
                    :senewredirecturllabelhelp="'{{$theUser->getProfileHelp('se_new_redirect_url')}}'"
                    :userdefaultlablabel="'After creation of SE, redirect to Page'"
                    :userdefaultlaboptions="{{$theUser->getProfileDisplayValues('default_lab')}}"
                    :userdefaultlabvmodel="'{{$theUser->getProfileValue("default_lab")}}'"
                    :userdefaultlablabelhelp="'{{$theUser->getProfileHelp('default_lab')}}'"
                    :defaultymethodlabel="'Default Mito Method'"
                    :defaultmitomethodoptions="{{$theUser->getProfileDisplayValues('default_mito_method')}}"
                    :defaultmitomethodvmodel="'{{$theUser->getProfileValue("default_mito_method")}}'"
                    :defaultmitomethodlabelhelp="'{{$theUser->getProfileHelp('default_mito_method')}}'"
                    :defaultymethodlabel="'Default Y Method'"
                    :defaultymethodoptions="{{$theUser->getProfileDisplayValues('default_y_method')}}"
                    :defaultymethodvmodel="'{{$theUser->getProfileValue("default_y_method")}}'"
                    :defaultymethodlabelhelp="'{{$theUser->getProfileHelp('default_y_method')}}'"
                    :defaultautomethodlabel="'Default Auto Method'"
                    :defaultautomethodoptions="{{$theUser->getProfileDisplayValues('default_auto_method')}}"
                    :defaultautomethodvmodel="'{{$theUser->getProfileValue("default_auto_method")}}'"
                    :defaultautomethodlabelhelp="'{{$theUser->getProfileHelp('default_auto_method')}}'"
                    :consensusdnauseoldlabel="'Use older DNA sample'"
                    :consensusdnauseoldoptions="{{json_encode($theUser->getProfileValue("consensus_dna_use_old"), true)}}"
                    :consensusdnauseoldlabelhelp="'{{$theUser->getProfileHelp('consensus_dna_use_old')}}'"

                    :table_data="{{$SEactivity}}"
                    :dna_table_data="{{$DNAactivity}}"
                    :switcher="true"
                    :pages_options="{{$theUser->getProfileDisplayValues('default_y_method')}}"
                    :options="{{$theUser->getProfileDisplayValues('default_auto_method')}}"
                    :options="{{$theUser->getProfileDisplayValues('default_mito_method')}}"
                    :csrf="'{{ csrf_token() }}'"
                    :user_id="{{$theUser->id}}"
                    :base_url="{{json_encode(url('/'))}}">
            </user-profile-main>
        </v-col>
    </v-row>
@endsection
