@extends('layouts.app')

@section('content')
{!! Form::open(['url' => 'reports/skeletalelements']) !!}
        <!-- Display Validation Errors -->
@include('common.errors')
@include('common.flash')

<div class="card">
    <div class="card-header">
        <div class="float-right">
            <div class="form-group">
                {!! Form::button('<i class="fas fa-btn fa-list"></i>Generate', ['type' => 'submit', 'class' => 'btn btn-primary','dusk'=>'report-generate']) !!}
            </div>
        </div>
        <div><h3 style="text-align:center;">{{$heading}}</h3></div>
    </div>

    <div class="card-body" style="padding-top: 0px; padding-bottom: 0px;">
        <table class="table skeletalelement-table" style="margin-bottom: 0px;">
            <tbody>
            <tr>
                <td><div class="form-group">
                    <div class="col-lg-3">{!! Form::label('select', 'Bones', ['class' => 'control-label']) !!}</div>
                    <div class="col-lg-9">{{ Form::select('sb_id', $list_sb, $sb_id, ['id' => 'sb', 'placeholder' => 'Select Bone', 'class' => 'mav-select','dusk'=>'report-select-bone']) }}</div>
                </div></td>
                <td><div class="form-group">
                    <div class="col-lg-3">{!! Form::label('select', 'Side', ['class' => 'control-label']) !!}</div>
                    <div class="col-lg-9">{{ Form::select('side', $list_side, $side, ['id' => 'side', 'placeholder' => 'Select Side', 'class' => 'mav-select','dusk'=>'report-select-side']) }}</div>
                </div></td>
            </tr>
            <tr>
                <td><div class="form-group">
                    <div class="col-lg-3">{!! Form::label('select', 'Completeness', ['class' => 'control-label']) !!}</div>
                    <div class="col-lg-9">{{ Form::select('completeness', $list_completeness, $completeness, ['id' => 'completeness', 'placeholder' => 'Select Completeness', 'class' => 'mav-select','dusk'=>'report-select-completeness']) }}</div>
                </div></td>
                <td><div class="form-group">
                    <div class="col-lg-3">{!! Form::label('checkbox', 'Inventory Completed') !!}</div>
                    <div class="col-lg-9">{{ Form::hidden('inventoried', false) }}{{ Form::checkbox('inventoried', true, $inventoried) }}</div>
                </div></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
{!! Form::close() !!}

@if ($skeletalelements != null)
    <div class="card">
        <div class="card-body">
            <table class="table table-striped mav-datatable-report">
                <thead> <!-- Table Headings -->
                {{--<th>Name</th><th>Program</th><th>Major</th><th>Status</th><th>G-Term</th><th>Prob</th><th class='no-sort'>Action</th>--}}
                <th>Key</th><th>Size</th><th>Completeness</th><th>Sampled</th><th>Inventory Completed</th>
                </thead>
                <tbody> <!-- Table Body -->
                @foreach ($skeletalelements as $skeletalelement)
                    <tr>
                        @if ( $open_result_new_tab )
                            <td class="table-text"><div><a href="{{ url('/skeletalelements/'.$skeletalelement->id) }}" target="_blank">{{ $skeletalelement->key }} </a></div></td>
                        @else
                            <td class="table-text"><div><a href="{{ url('/skeletalelements/'.$skeletalelement->id) }}">{{ $skeletalelement->key }}</a></div></td>
                        @endif
                        <td class="table-text"><div>{{ $skeletalelement->side }}</div></td>
                        <td class="table-text"><div>{{ $skeletalelement->completeness }}</div></td>
                        @if ($skeletalelement->sampled)
                            <td class="table-text text-success"><div>&#10004</div></td>
                        @endif
                        @if ($skeletalelement->inventoried)
                            <td class="table-text text-success"><div>&#10004</div></td>
                        @endif
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endif

@stop

@section('footer')
    <style>
        .table td { border: 0px !important; }
        .table td { padding: 2px !important; }
        .table th { padding: 2px !important; }
        div.col-lg-10 { padding: 2px !important; }
        .table td select { margin: 0px !important; }
        div.card-body {padding: 5px !important; }
        a.dt-button { padding: 5px !important }
        .dataTables_wrapper .dt-buttons { float:none; text-align:center; }
        table.mav-datatable-report {margin-top: 25px !important;}
        div.dt-buttons { width: 75%; position: relative; left: 100px; }
    </style>

    {{--The cdn.datatables.net SRI where generated by Sachin--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" integrity="sha256-1QhqWkX+/a13PvcHGu1ef6cpzB2fTC1AQSKO1/CNl7o= sha384-+HuqSo2jltxblyQxEWXqMxros/OMTbQj97cQmCg02u0tDBM6ua+n6riJITcaYLZv sha512-sEbniBlNhlkA+FO5+JoHk/FiugGQECr07pQPR4q2tuREh2q4LCdSZ/519yqxt/fGZqwm1GZdHccu6H0SdKohrA==" crossorigin="anonymous">
    {{--<link href="https://cdn.datatables.net/buttons/1.4.2/css/buttons.dataTables.min.css" rel="stylesheet" />--}}

    <script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js" integrity="sha256-JX8A01otZNUwZ/96fg38qJJEqjeDEHUgovDYIhusby4= sha384-6HTzjzs9z4e++DpwUslzHjPEQLurPtfOOr1EENaFoaLY2XTdteWLxIaTdSm+G+Z7 sha512-usceWqMONV4+a/yaBewx8Q9UCdp+7kkyRyKp4fxB0LvKQ7g9gQ1iS6ztYt4eshGeuygBAPIOvKvQsPYVq838Zg==" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js" integrity="sha256-nO6twHurwTTWWCM5jC3c5MRWsd1GkOsSFc1SNoFpk6g= sha384-ZbRaugJJbCmrmnyQcZU1fqaWT2VXtHoNIK9EJH63nsc+F+GOnY5pipIUBOKT/Aga sha512-g7r79V2H5EirPopoNeFbLqCxvB3qFOK4bLCY17+X44KrdQhwFOt2UPzLRoThU+zlTw+5ysncnO/z9TYCHAPLmA==" crossorigin="anonymous"></script>
    {{--<script src="https://cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>--}}
    {{--<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.flash.min.js"></script>--}}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.4/jszip.min.js" integrity="sha256-/1hjUCFxE/1IivzFCHoS/Et2IQ3z79iNnk42PkZeXhA=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.33/pdfmake.min.js" integrity="sha256-g/E4VHjOmUR6XM3rS0ysSAamcAopVJSGDCyj7A/BN3M=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.33/vfs_fonts.js" integrity="sha256-HM47olZz1oQ8keYmS4UQy/EypVZ8gpFenpuNeYQib+g=" crossorigin="anonymous"></script>

    <script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js" integrity="sha256-3Q7fE5fiylv3agZcVLKCywHVtuDSHSXKM5YIr/Z0FpM= sha384-MGofXzcROcQ3bZUqtn2mEI8nhXNmKZ9Qq4FcEapwT3JBKUlgVY+ngyYFNXXUgzSS sha512-/JfTyPFuqrC3Kpbg05uMvVGrDzNUal4xOGJZevKKP8ikOIKHJT9Ux+Fu3mGsncRxqVr0krmkblmv8pkMWIvHmA==" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js" integrity="sha256-gsf4GD4Wlg76ZDLglWHFgx4B0Q4rviAxS0mOkRsFs94= sha384-6LRoAn1kvkBMPNsHa6Y/6XDwiX/0cU1FHViqG3kokG9eJ3y0xM1rjQNRxprscuX6 sha512-JybXwXemGVGYrz28jIbszgT5QIh0K2xxVAwOU0VUDarDbGWyKODeCRBEBqOR7ObL1pWhDjQorA4lhwYlUHMDOA==" crossorigin="anonymous"></script>
    {{--<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.html5.min.js"></script>--}}
    {{--<script src="https://cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>--}}

    <script>
        $(document).ready(function($){
            $('table.mav-datatable-report').DataTable( {
//                dom: 'lfBrtip',
                dom: 'Bfrtlip',
                buttons: ['pageLength', 'excel', 'pdf', 'colvis']
            } );

            $('#program').change(function(e){
                var program_id = e.target.value;
                $.get("{{ url('api/major-DropDownData')}}",
                        { option: $(this).val() },
                        function(data) {
                            $('#major').empty();
                            $.each(data, function(key, element) {
                                // alert("Hello! I am an alert box!!");
                                $('#major').append("<option value='" + key +"'>" + element + "</option>");
                            });
                        });
            });

            $('a.dt-button').addClass('fas fa-btn');
            $('a.buttons-pdf').addClass('fa-file-pdf-o');
            $('a.buttons-excel').addClass('fa-file-excel-o');
            $('a.buttons-csv').addClass('fa-file-text-o');
            $('a.buttons-copy').addClass('fa-copy');
            $('a.buttons-print').addClass('fa-print');
            $('a.dt-button > span').each(function() {
                var title = $( this ).text();
                $(this).text(" " + title);
            });
//            $('a.dt-button > span').remove();

            $('table.skeletalelement-table select').select2();
        });

    </script>
@stop
