@extends('layouts.app')

@section('title', config('app.name', 'CoRA')." ".$heading)

@section('content')
    <v-row align="center" justify="center">
        <v-col cols="12" class="m-0 p-0">
            <org-profile-main
                    :disabled="false"
                    :csrf="'{{ csrf_token() }}'"
                    :base_url="{{json_encode(url('/'))}}"
                    :orgnamelabel="'Organization Name:'"
                    :orgnamevmodel="{{json_encode($theOrg->name)}}"
                    :org_acronymlabel="'Organization Acronym:'"
                    :org_acronymvmodel="{{json_encode($theOrg->acronym)}}"
                    :org_descriptionlabel="'Organization Description:'"
                    :org_descriptionvmodel="{{json_encode($theOrg->description)}}"
                    :addresslabel="'Address:'"
                    :addressvmodel="{{json_encode($theOrg->address)}}"
                    :citylabel="'City:'"
                    :cityvmodel="{{json_encode($theOrg->city)}}"
                    :statelabel="'State:'"
                    :statevmodel="{{json_encode($theOrg->state)}}"
                    :ziplabel="'Zip Code:'"
                    :zipvmodel="{{json_encode($theOrg->zip)}}"
                    :websitelabel="'Website URL:'"
                    :websitevmodel="{{json_encode($theOrg->website)}}"
                    :phone_number="{{json_encode($theOrg->phone)}}"
                    :phone_label="{{json_encode(trans('labels.phone'))}}"
                    :tfphone="{{json_encode($theOrg->toll_free)}}"
                    :tfphone_label="{{json_encode(trans('labels.toll_free_phone'))}}"
                    :fax_number="{{json_encode($theOrg->fax)}}"
                    :fax_label="{{json_encode(trans('labels.fax'))}}"
                    :contact_name="{{json_encode($theOrg->contact_name)}}"
                    :contact_name_label="{{json_encode(trans('labels.contact_name'))}}"
                    :contact_email="{{json_encode($theOrg->contact_email)}}"
                    :contact_email_label="{{json_encode(trans('labels.contact_email'))}}"
                    :geo_lat="{{json_encode($theOrg->geo_lat)}}"
                    :geo_lat_label="{{json_encode(trans('labels.geo_lat'))}}"
                    :geo_long="{{json_encode($theOrg->geo_long)}}"
                    :geo_long_label="{{json_encode(trans('labels.geo_long'))}}"
                    :welcomescreenlabel="{{json_encode(trans('labels.welcome_screen_url'))}}"
                    :welcomescreenlabelhelp="{{json_encode($theOrg->getProfileHelp('welcome_screen_url'))}}"
                    :welcomescreenvalue="{{json_encode($theOrg->getProfileValue('welcome_screen_url'))}}"
                    :addcorademoprojectslabelhelp="{{json_encode($theOrg->getProfileHelp('add_cora_demo_project_for_new_users'))}}"
                    :addcorademoprojectslabel="{{json_encode(trans('labels.add_demo_project'))}}"
                    :addcorademoprojectsvalue="{{json_encode($theOrg->getProfileValue("add_cora_demo_project_for_new_users"))}}"
                    :countries_options="{{json_encode($country_array, true)}}"
                    :languages_options="{{json_encode($language_codes, true)}}"
                    :timezones_options="{{json_encode($timezone_array, true)}}"
                    :default_country="{{json_encode($theOrg->default_country, true)}}"
                    :default_language="{{json_encode($theOrg->default_language, true)}}"
                    :default_time_zone="{{json_encode($theOrg->default_timezone, true)}}"
                    :massunitoptions="{{$theOrg->getProfileDisplayValues('org_mass_unit_of_measure')}}"
                    :lengthunitoptions="{{$theOrg->getProfileDisplayValues('org_length_unit_of_measure')}}"
                    :lengthunitvmodel="'{{$theOrg->getProfileValue('org_length_unit_of_measure')}}'"
                    :massunitvmodel="'{{$theOrg->getProfileValue('org_mass_unit_of_measure')}}'"
                    :massunitlabelhelp="'{{$theOrg->getProfileHelp('org_mass_unit_of_measure')}}'"
                    :lengthunitlabelhelp="'{{$theOrg->getProfileHelp('org_length_unit_of_measure')}}'"
                    :massunitlabel="'Mass Unit'"
                    :lengthunitlabel="'Length Unit'"
                    :slackwebhooklabel="'Slack Webhook'"
                    :slackchannellabel="'Slack Channel'"
                    :googlemapslabel= "'Google Maps'"
                    :slackwebhooklabelhelp="'{{ $theOrg->getProfileHelp('org_api_slack_webhook') }}'"
                    :slackchannellabelhelp="'{{ $theOrg->getProfileHelp('org_api_slack_channel') }}'"
                    :googlemapslabelhelp="'{{ $theOrg->getProfileHelp('org_api_google_maps') }}'"
                    :slackwebhookvmodel="'{{$theOrg->getProfileValue('org_api_slack_webhook')}}'"
                    :slackchannelvmodel="'{{$theOrg->getProfileValue('org_api_slack_channel')}}'"
                    :googlemapsvmodel="'{{$theOrg->getProfileValue('org_api_google_maps')}}'"
                    :org_id="{{$theOrg->id}}">
            </org-profile-main>
        </v-col>
    </v-row>
@endsection
